"""initial schema

Revision ID: 90cacd044a8c
Revises: 
Create Date: 2025-12-28 21:44:50.929029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90cacd044a8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_equity_curve_simulation_id_date'), table_name='simulation_equity_curve')
    op.create_index(op.f('ix_simulation_equity_curve_id'), 'simulation_equity_curve', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_equity_curve_simulation_id'), 'simulation_equity_curve', ['simulation_id'], unique=False)
    op.drop_index(op.f('ix_simulation_trades_simulation_id_date'), table_name='simulation_trades')
    op.create_index(op.f('ix_simulation_trades_id'), 'simulation_trades', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_trades_simulation_id'), 'simulation_trades', ['simulation_id'], unique=False)
    op.alter_column('simulations', 'batch_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('simulations', 'batch_group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('simulations', 'params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('simulations', 'params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('simulations', 'batch_group_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('simulations', 'batch_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_simulation_trades_simulation_id'), table_name='simulation_trades')
    op.drop_index(op.f('ix_simulation_trades_id'), table_name='simulation_trades')
    op.create_index(op.f('ix_simulation_trades_simulation_id_date'), 'simulation_trades', ['simulation_id', 'date'], unique=False)
    op.drop_index(op.f('ix_simulation_equity_curve_simulation_id'), table_name='simulation_equity_curve')
    op.drop_index(op.f('ix_simulation_equity_curve_id'), table_name='simulation_equity_curve')
    op.create_index(op.f('ix_simulation_equity_curve_simulation_id_date'), 'simulation_equity_curve', ['simulation_id', 'date'], unique=False)
    # ### end Alembic commands ###
